"""empty message

Revision ID: 2a43e088887d
Revises: d352f7221b85
Create Date: 2021-12-03 09:48:02.119377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a43e088887d'
down_revision = 'd352f7221b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.add_column('post', sa.Column('abstract', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('abstract', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
